server:
  port: 5058
  
#View Resolver
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp  

#DataSource Config values

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql:true
        format_sql:true
        dialect:org.hibernate.dialect.OracleDialect
    show-sql: true
    
   
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: 12345678
    url: jdbc:oracle:thin:@localhost:1521:orcl
  
  